name: Deploy Lab
on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    name: Deploy to Deno Deploy
    runs-on: ubuntu-latest
    permissions:
      id-token: write # Needed for auth with Deno Deploy
      contents: read # Needed to clone the repository

    steps:
      - name: Clone repository
        uses: actions/checkout@v3
      - name: Deno Deploy
        uses: denoland/deployctl@v1
        with:
          project: snendev-lab
          entrypoint: main.ts
